### PR TITLE
Llm params

### PR DESCRIPTION
**Pull request by ABHISHEK03312**
**Description:** Fixed the OpenLLM python client to be able to edit LLM config parameters when sending requests. 
**Issue:** Currently to use the client with necessary user configuration, the openllm bento needs to be edited. For testing purposes this can become quite tedious, to keep editing the configuration in the bentos and query the LLM server. 
**Dependency:** No additional dependencies.
**Tests:** Sample codes have been included in the main directory under sample-tests folder.  

@aarnphm

### CODE REVIEW

**Comment by aarnphm** [comment]
Sorry what does this PR add?

`query` and `generate` should already accept llm parameters on each request. see `llm_config`.

This seems to me like a code golf PR. Is there anything specific difference about this other than style change?

**Comment by aarnphm** [comment]
I will close this since I didn't see anything difference. I will check your other PR. Thanks

**Comment by ABHISHEK03312** [comment]
Hi, thank you for checking in. I noticed that the query method, always uses the default configurations for the Model. For example, if the model is deployed with max_tokens 128, then the same is used for subsequent queries. The other `LLM_config` params behave the same way. Therefore, I added an update feature to be able to change the configuration when the user uses the query method. 

As for your concern over using `LLM_config`, the LLM config is uses as a whole new dictionary key in the final configuration. 
Example; 
`client.query(llm_config  = {max_new_tokens:2000})`, the final configuration is reflected as 
`{llm_config ; {max_new_tokens:2000}, generation_config : {default_llm_config}`
This is the above problem that i am trying to fix since at the end of the day the model uses generation config params and not the `LLM_config`. 

Do take a look at the changes once again @aarnphm.
Thanks

**Comment by aarnphm** [comment]
This is actually fixed to since all items are dumped flatten, so it will correspond correctly now. I have tested this with 0.4.0

**Comment by aarnphm** [comment]
Screenshot 2023-11-08 at 01 33 49
That request is proccessed with
```python
client.generate("What is the definition of time?", max_new_tokens=12)
```

If you don't pass any generation config
```python
client.generate("What is the definition of time?")
```

If you see the default value is used here
Screenshot 2023-11-08 at 01 35 03

**Comment by aarnphm** [comment]
Screenshot 2023-11-08 at 01 35 53

You can clearly sees the difference here.

**Pull request closed without merging**
